# Setup
title: Niraj Sapkota
url: https://notes.nirajsapkota.com
paginate: 1
baseurl: "/Notes"
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Niraj Sapkota
  url: https://twitter.com/mdo
  email: n.sapkota@outlook.com.au

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Website
    url: https://nirajsapkota.com

  - title: GitHub
    url: https://github.com/nirajsapkota
  
  - title: LinkedIn
    url: https://linkedin.com/in/nirajsapkota
